# Generated by Django 6.0.3 on 2026-04-08 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable flag name', max_length=100, unique=True)),
                ('key', models.SlugField(help_text='Code identifier, e.g. enable_ai_calls', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this flag controls')),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('user_deleted', 'User Deleted'), ('plan_assigned', 'Plan Assigned'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_extended', 'Subscription Extended'), ('trial_granted', 'Trial Granted'), ('progress_reset', 'Progress Reset'), ('flag_toggled', 'Feature Flag Toggled'), ('premium_granted', 'Premium Granted Manually'), ('note_added', 'Admin Note Added')], max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='saas_admin__admin_i_0ca235_idx'), models.Index(fields=['target_user'], name='saas_admin__target__5cb909_idx'), models.Index(fields=['action'], name='saas_admin__action_b00910_idx')],
            },
        ),
    ]
