# Generated by Django 6.0 on 2025-12-31 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
        ('roadmap_ai', '0010_studentproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='forks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='last_commit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='last_commit_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='project_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap Project'), ('student', 'Student Project')], default='roadmap', max_length=20),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='stars_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='student_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_repo', to='roadmap_ai.studentproject'),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='watchers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_repo', to='roadmap_ai.project'),
        ),
    ]
