# Generated by Django 5.2.7 on 2026-01-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lifecycleevent',
            new_name='user_lifecy_user_id_5def59_idx',
            old_name='user_lifecy_user_id_77b9ff_idx',
        ),
        migrations.RenameIndex(
            model_name='lifecycleevent',
            new_name='user_lifecy_user_id_2c657e_idx',
            old_name='user_lifecy_user_id_aa0e90_idx',
        ),
    ]
