# Generated by Django 6.0 on 2025-12-29 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap_ai', '0009_roadmap_faqs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('custom_subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('read_only', 'Read Only'), ('archived', 'Archived')], default='archived', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('show_email', models.BooleanField(default=False)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_status_change', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('project_clicks', models.IntegerField(default=0)),
                ('github_clicks', models.IntegerField(default=0)),
                ('resume_downloads', models.IntegerField(default=0)),
                ('referrer_data', models.JSONField(default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('custom_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='portfolio.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='roadmap_ai.project')),
            ],
            options={
                'ordering': ['-is_featured', 'order'],
                'unique_together': {('portfolio', 'project')},
            },
        ),
    ]
