# Generated by Django 6.0 on 2025-12-31 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('roadmap_ai', '0010_studentproject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolioproject',
            name='unique_portfolio_project',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='project_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap Project'), ('student', 'Student Project')], default='roadmap', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='student_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='roadmap_ai.studentproject'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='roadmap_ai.project'),
        ),
    ]
