# Generated by Django 5.2.5 on 2026-03-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolioproject_unique_portfolio_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('cta_click', 'CTA Click'), ('project_click', 'Project Click'), ('resume_click', 'Resume Click')], max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='availability_status',
            field=models.CharField(choices=[('open', 'Open to opportunities'), ('interviewing', 'Interviewing'), ('not_looking', 'Not actively looking')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='primary_cta_label',
            field=models.CharField(default='Hire Me', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='primary_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='resume_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seo_description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seo_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='duration_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='impact_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['status'], name='portfolio_p_status_c9d472_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_published'], name='portfolio_p_is_publ_ba102e_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['status', 'is_published'], name='portfolio_p_status_cafa91_idx'),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portfolio.portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['portfolio', 'event_type', 'created_at'], name='portfolio_p_portfol_606a12_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['created_at'], name='portfolio_p_created_ae8dca_idx'),
        ),
    ]
