# Generated by Django 6.0 on 2025-12-29 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap_ai', '0009_roadmap_faqs'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_roadmaps_completed', models.IntegerField(default=0)),
                ('total_projects_completed', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('total_resumes_created', models.IntegerField(default=0)),
                ('total_ats_scans', models.IntegerField(default=0)),
                ('total_study_minutes', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.IntegerField(default=0)),
                ('projects_worked', models.IntegerField(default=0)),
                ('resumes_created', models.IntegerField(default=0)),
                ('ats_scans_run', models.IntegerField(default=0)),
                ('minutes_active', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestones_completed', models.IntegerField(default=0)),
                ('total_milestones', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='roadmap_ai.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'roadmap')},
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('roadmap_create', 'Roadmap Created'), ('project_create', 'Project Created'), ('resume_create', 'Resume Created'), ('ats_scan', 'ATS Scan'), ('github_publish', 'GitHub Publish'), ('portfolio_view', 'Portfolio View')], max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='analytics_u_user_id_92c86d_idx'), models.Index(fields=['created_at'], name='analytics_u_created_5b63bc_idx')],
            },
        ),
    ]
