# Generated by Django 5.2.7 on 2026-01-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_validation_framework'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskattempt',
            name='unique_task_attempt',
        ),
        migrations.RenameIndex(
            model_name='taskattempt',
            new_name='tasks_taska_user_id_5b32f0_idx',
            old_name='tasks_taska_user_id_validat_idx',
        ),
        migrations.RenameIndex(
            model_name='taskattempt',
            new_name='tasks_taska_task_id_4673c2_idx',
            old_name='tasks_taska_task_id_submit_idx',
        ),
        migrations.AlterUniqueTogether(
            name='taskattempt',
            unique_together={('task', 'attempt_number')},
        ),
    ]
