# Generated by Django 5.2.5 on 2026-01-16 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0012_task'),
        ('tasks', '0003_remove_taskattempt_unique_task_attempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskValidator',
            fields=[
                ('validator_id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Human Review'), ('APPROVED', 'Approved'), (
                    'REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision')], default='PENDING', max_length=20)),
                ('score', models.FloatField(blank=True,
                 help_text='Human-assigned score (0-100)', null=True)),
                ('feedback', models.TextField(blank=True,
                 help_text='Human feedback on submission')),
                ('improvement_notes', models.TextField(
                    blank=True, help_text='Suggestions for improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='taskattempt',
            name='tasks_taska_user_id_5b32f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskattempt',
            name='tasks_taska_task_id_4673c2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='taskattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='acceptance_rules',
            field=models.JSONField(
                blank=True, default=dict, help_text='Validator-specific rules (min_commits, required_files, answer_key, etc)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_core_task',
            field=models.BooleanField(
                default=False, help_text='Core tasks required for output eligibility'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_attempts',
            field=models.IntegerField(
                blank=True, help_text='Max attempts allowed (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='objective',
            field=models.TextField(
                blank=True, help_text='Measurable outcome - what needs to be proven'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='validator_type',
            field=models.CharField(choices=[('AUTO_GITHUB', 'Automated GitHub Validator'), ('AUTO_QUIZ', 'Automated Quiz Validator'), (
                'MANUAL', 'Manual Human Review'), ('none', 'No Validation')], default='none', help_text='How proof will be validated', max_length=20),
        ),
        migrations.RemoveField(
            model_name='taskattempt',
            name='id',
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='attempt_id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='proof_hash',
            field=models.CharField(
                db_index=True, default=1, help_text='SHA256 of task+user+payload - prevents proof reuse', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='proof_payload',
            field=models.JSONField(
                default=dict, help_text="User's submitted proof (repo URL, quiz answers, file path, etc.)"),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='validator_output',
            field=models.JSONField(
                blank=True, default=dict, help_text='Complete validator response (status, checks, errors, etc)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='can_edit_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='can_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='task_contracts', to='roadmap_ai.milestone'),
        ),
        migrations.AlterField(
            model_name='task',
            name='minimum_pass_score',
            field=models.FloatField(
                default=70.0, help_text='Minimum score (0-100) required'),
        ),
        migrations.AlterField(
            model_name='task',
            name='proof_type',
            field=models.CharField(choices=[('GITHUB_REPO', 'GitHub Repository'), ('QUIZ', 'Quiz'), ('FILE_UPLOAD', 'File Upload'), (
                'URL', 'Live URL'), ('none', 'No Validation Required')], default='none', help_text='Type of proof required', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='task_contracts', to='roadmap_ai.roadmap'),
        ),
        migrations.AlterField(
            model_name='task',
            name='validator_data',
            field=models.JSONField(
                blank=True, default=dict, help_text='[LEGACY] Old validator configuration'),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='attempt_number',
            field=models.IntegerField(help_text='Attempt count for this task'),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='score',
            field=models.FloatField(
                blank=True, help_text='Validation score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('PASS', 'Passed'), (
                'FAIL', 'Failed')], default='PENDING', help_text='Validation result: PENDING, PASS, or FAIL', max_length=10),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_core_task'],
                               name='tasks_task_is_core_7fb7bb_idx'),
        ),
        migrations.AddField(
            model_name='taskvalidator',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='task_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='manual_review',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt', to='tasks.taskvalidator'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=[
                               'user', 'task', 'validation_status'], name='tasks_taska_user_id_d0aa86_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(
                fields=['user', '-submitted_at'], name='tasks_taska_user_id_bfc97f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(
                fields=['task', 'validation_status'], name='tasks_taska_task_id_ebda53_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskattempt',
            constraint=models.UniqueConstraint(
                fields=('task', 'user', 'attempt_number'), name='unique_task_attempt'),
        ),
        migrations.RemoveField(
            model_name='taskattempt',
            name='proof_data',
        ),
        migrations.RemoveField(
            model_name='taskattempt',
            name='validator_feedback',
        ),
        migrations.AddIndex(
            model_name='taskvalidator',
            index=models.Index(
                fields=['reviewer', 'review_status'], name='tasks_taskv_reviewe_1bcd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskvalidator',
            index=models.Index(
                fields=['review_status'], name='tasks_taskv_review__11edc1_idx'),
        ),
    ]
