# Generated by Django 6.0.3 on 2026-05-25 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roadmap_id', models.UUIDField(blank=True, help_text='FK reference to roadmap (UUID to avoid cross-app FK)', null=True)),
                ('change_type', models.CharField(choices=[('workload_reduction', 'Workload Reduction'), ('challenge_increase', 'Challenge Increase'), ('easy_win_injection', 'Easy Win Injection'), ('theory_practical_rebalance', 'Theory-to-Practical Rebalance')], max_length=50)),
                ('description', models.TextField()),
                ('suggested_changes', models.JSONField(blank=True, default=list)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('trigger_metrics', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'applied'], name='intelligenc_user_id_ab1aa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehavioralInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(help_text='behavioral, momentum, prediction, roadmap, identity, loop, adaptation', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence', models.FloatField(default=0, help_text='0-100 confidence score')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('strategy', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_action', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(choices=[('encouraging', 'Encouraging'), ('cautioning', 'Cautioning'), ('celebrating', 'Celebrating'), ('neutral', 'Neutral')], default='neutral', max_length=30)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='intelligenc_user_id_dea43c_idx'), models.Index(fields=['user', 'insight_type'], name='intelligenc_user_id_794a47_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('task_started', 'Task Started'), ('task_completed', 'Task Completed'), ('task_skipped', 'Task Skipped'), ('task_delayed', 'Task Delayed'), ('task_reopened', 'Task Reopened'), ('task_abandoned', 'Task Abandoned'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('session_quit', 'Session Quit'), ('session_interrupted', 'Session Interrupted'), ('roadmap_opened', 'Roadmap Opened'), ('roadmap_progress_updated', 'Roadmap Progress Updated'), ('roadmap_abandoned', 'Roadmap Abandoned'), ('roadmap_completed', 'Roadmap Completed'), ('roadmap_switched', 'Roadmap Switched'), ('ai_coach_opened', 'AI Coach Opened'), ('ai_strategy_requested', 'AI Strategy Requested'), ('voice_coach_used', 'Voice Coach Used'), ('insight_clicked', 'Insight Clicked')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.UUIDField(blank=True, help_text='Groups events that belong to the same user session', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='intelligenc_user_id_0a99aa_idx'), models.Index(fields=['user', 'created_at'], name='intelligenc_user_id_b79a7f_idx'), models.Index(fields=['user', 'event_type', 'created_at'], name='intelligenc_user_id_fe8c02_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('motivation_crash', 'Motivation Crash Loop'), ('avoidance', 'Avoidance Loop'), ('planning_addiction', 'Planning Addiction Loop'), ('fake_productivity', 'Fake Productivity Loop')], max_length=50)),
                ('description', models.TextField()),
                ('detection_data', models.JSONField(blank=True, default=dict)),
                ('occurrences', models.IntegerField(default=1)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_detected'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='intelligenc_user_id_402435_idx'), models.Index(fields=['user', 'pattern_type'], name='intelligenc_user_id_c340d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyBehaviorSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('momentum_score', models.FloatField(default=0)),
                ('burnout_risk', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('dropoff_risk', models.FloatField(default=0)),
                ('procrastination_index', models.FloatField(default=0)),
                ('recovery_speed', models.FloatField(default=0)),
                ('active_minutes', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_skipped', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('preferred_hour', models.IntegerField(blank=True, null=True)),
                ('identity_type', models.CharField(blank=True, max_length=50)),
                ('raw_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='intelligenc_user_id_5213bc_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
