# Generated by Django 5.2.7 on 2025-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_pomodoros',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
