# Generated by Django 6.0.3 on 2026-04-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_execution_engine_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executiontask',
            new_name='dashboard_e_user_id_ac1b3a_idx',
            old_name='dashboard_ex_user_id_cbde44_idx',
        ),
        migrations.RenameIndex(
            model_name='executiontask',
            new_name='dashboard_e_user_id_4eea09_idx',
            old_name='dashboard_ex_user_id_061fd2_idx',
        ),
    ]
