# Generated by Django 6.0 on 2025-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('explorer', 'Explorer'), ('starter', 'Starter Builder'), ('career_ready', 'Career Ready'), ('placement_pro', 'Placement Pro')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_days', models.IntegerField()),
                ('roadmap_limit', models.IntegerField(help_text='Number of roadmaps allowed')),
                ('is_short_roadmap', models.BooleanField(default=False, help_text='True for Explorer plan short roadmaps')),
                ('project_limit_min', models.IntegerField(help_text='Minimum projects allowed')),
                ('project_limit_max', models.IntegerField(help_text='Maximum projects allowed')),
                ('resume_limit', models.IntegerField(help_text='Number of resume versions allowed, -1 for time-bound unlimited')),
                ('ats_scan_limit', models.IntegerField(help_text='Number of ATS scans, -1 for rate-limited unlimited')),
                ('ats_rate_limit_per_day', models.IntegerField(default=0, help_text='Daily rate limit for unlimited plans')),
                ('portfolio_analytics', models.BooleanField(default=False)),
                ('custom_subdomain', models.BooleanField(default=False, help_text='name.platform.com')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_inr'],
            },
        ),
    ]
