# Generated by Django 5.2.5 on 2026-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='custom_subdomain',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_short_roadmap',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='portfolio_analytics',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='project_limit_max',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='project_limit_min',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='resume_limit',
        ),
        migrations.AddField(
            model_name='plan',
            name='has_async_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_early_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_portfolio_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_project_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_resources_hub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='job_finder_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='portfolio_addon_price_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 if included, >0 if addon', max_digits=6),
        ),
        migrations.AddField(
            model_name='plan',
            name='quicky_ai_daily_limit',
            field=models.IntegerField(default=5, help_text='Daily AI query limit, -1 for unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='resume_full',
            field=models.BooleanField(default=False, help_text='Full resume generator vs basic'),
        ),
        migrations.AddField(
            model_name='plan',
            name='session_duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='sessions_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ats_rate_limit_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ats_scan_limit',
            field=models.IntegerField(default=0, help_text='ATS scans allowed, -1 for unlimited, 0 for none'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='roadmap_limit',
            field=models.IntegerField(help_text='Roadmaps per month, -1 for unlimited'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity_days',
            field=models.IntegerField(default=30),
        ),
    ]
