import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export default function SupportPage() {
    const [activeTab, setActiveTab] = useState('feedback');
    const [formData, setFormData] = useState({
        type: 'feedback',
        subject: '',
        message: '',
        priority: 'normal',
        email: ''
    });
    const [submitted, setSubmitted] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);

        // Simulate submission
        await new Promise(resolve => setTimeout(resolve, 1500));

        setSubmitted(true);
        setLoading(false);

        // Reset after 3 seconds
        setTimeout(() => {
            setSubmitted(false);
            setFormData({
                type: 'feedback',
                subject: '',
                message: '',
                priority: 'normal',
                email: ''
            });
        }, 3000);
    };

    const feedbackTypes = [
        { id: 'feedback', label: '💭 General Feedback', description: 'Share your thoughts about Planorah' },
        { id: 'bug', label: '🐛 Report a Bug', description: 'Something not working? Let us know' },
        { id: 'feature', label: '✨ Feature Request', description: 'Have an idea? We would love to hear it' },
        { id: 'complaint', label: '😔 Complaint', description: 'We are sorry. Tell us what went wrong' },
    ];

    const faqs = [
        { q: 'How do I create a learning roadmap?', a: 'Go to Learning → Learning Path and click "Create New Roadmap". Our AI will help you build a personalized plan!' },
        { q: 'Can I edit my roadmap after creation?', a: 'Currently, roadmaps are generated by AI. You can create a new one anytime with different goals.' },
        { q: 'How does the streak system work?', a: 'Complete at least one task per day to maintain your streak. Your streak resets if you miss a day.' },
        { q: 'Where can I see my progress?', a: 'Visit your Profile page to see all your statistics, completed tasks, and learning progress.' },
    ];

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-[#0A0A0A] py-8 px-4">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="text-center mb-10"
                >
                    <span className="inline-block px-4 py-1.5 bg-violet-100 dark:bg-violet-500/20 text-violet-700 dark:text-violet-400 text-xs font-semibold rounded-full mb-3 uppercase tracking-wide">
                        Support Center
                    </span>
                    <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-2">
                        We're Here to Help 💜
                    </h1>
                    <p className="text-gray-600 dark:text-gray-400 max-w-xl mx-auto">
                        Your voice matters to us. Share feedback, report issues, or request features – we read every message.
                    </p>
                </motion.div>

                {/* Tab Navigation */}
                <div className="flex justify-center mb-8">
                    <div className="inline-flex bg-white dark:bg-[#1C1C1E] rounded-full p-1.5 border border-gray-200 dark:border-gray-800">
                        {['feedback', 'faq', 'contact'].map((tab) => (
                            <button
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`px-6 py-2.5 rounded-full text-sm font-medium transition-all ${activeTab === tab
                                    ? 'bg-gray-900 dark:bg-white text-white dark:text-gray-900'
                                    : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white'
                                    }`}
                            >
                                {tab === 'feedback' && '📝 Feedback'}
                                {tab === 'faq' && '❓ FAQ'}
                                {tab === 'contact' && '📧 Contact'}
                            </button>
                        ))}
                    </div>
                </div>

                <AnimatePresence mode="wait">
                    {/* Feedback Form Tab */}
                    {activeTab === 'feedback' && (
                        <motion.div
                            key="feedback"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                        >
                            {submitted ? (
                                <motion.div
                                    initial={{ scale: 0.9, opacity: 0 }}
                                    animate={{ scale: 1, opacity: 1 }}
                                    className="bg-white dark:bg-[#1C1C1E] rounded-2xl border border-gray-200 dark:border-gray-800 p-12 text-center"
                                >
                                    <div className="w-20 h-20 bg-green-100 dark:bg-green-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
                                        <span className="text-4xl">✅</span>
                                    </div>
                                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Thank You!</h2>
                                    <p className="text-gray-600 dark:text-gray-400">Your feedback has been submitted. We'll review it shortly.</p>
                                </motion.div>
                            ) : (
                                <div className="bg-white dark:bg-[#1C1C1E] rounded-2xl border border-gray-200 dark:border-gray-800 overflow-hidden">
                                    {/* Type Selection */}
                                    <div className="p-6 border-b border-gray-200 dark:border-gray-800">
                                        <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-4">What would you like to share?</h3>
                                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                                            {feedbackTypes.map((type) => (
                                                <button
                                                    key={type.id}
                                                    onClick={() => setFormData({ ...formData, type: type.id })}
                                                    className={`p-4 rounded-xl text-left transition-all border ${formData.type === type.id
                                                        ? 'bg-violet-50 dark:bg-violet-500/10 border-violet-300 dark:border-violet-500'
                                                        : 'bg-gray-50 dark:bg-gray-900 border-gray-200 dark:border-gray-800 hover:border-gray-300 dark:hover:border-gray-700'
                                                        }`}
                                                >
                                                    <span className="text-2xl mb-2 block">{type.label.split(' ')[0]}</span>
                                                    <span className={`text-xs font-medium ${formData.type === type.id
                                                        ? 'text-violet-700 dark:text-violet-400'
                                                        : 'text-gray-600 dark:text-gray-400'
                                                        }`}>
                                                        {type.label.split(' ').slice(1).join(' ')}
                                                    </span>
                                                </button>
                                            ))}
                                        </div>
                                    </div>

                                    {/* Form */}
                                    <form onSubmit={handleSubmit} className="p-6 space-y-5">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                                Subject
                                            </label>
                                            <input
                                                type="text"
                                                value={formData.subject}
                                                onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                                                placeholder="Brief summary of your feedback"
                                                className="w-full px-4 py-3 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-violet-500/50 focus:border-violet-500"
                                                required
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                                Your Message
                                            </label>
                                            <textarea
                                                value={formData.message}
                                                onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                                                placeholder="Tell us more... We're listening 💜"
                                                rows={5}
                                                className="w-full px-4 py-3 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-violet-500/50 focus:border-violet-500 resize-none"
                                                required
                                            />
                                        </div>

                                        {formData.type === 'bug' && (
                                            <motion.div
                                                initial={{ opacity: 0, height: 0 }}
                                                animate={{ opacity: 1, height: 'auto' }}
                                            >
                                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                                    Priority Level
                                                </label>
                                                <div className="flex gap-3">
                                                    {['low', 'normal', 'high', 'critical'].map((p) => (
                                                        <button
                                                            key={p}
                                                            type="button"
                                                            onClick={() => setFormData({ ...formData, priority: p })}
                                                            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${formData.priority === p
                                                                ? p === 'critical'
                                                                    ? 'bg-red-100 dark:bg-red-500/20 text-red-700 dark:text-red-400 border border-red-300 dark:border-red-500'
                                                                    : p === 'high'
                                                                        ? 'bg-orange-100 dark:bg-orange-500/20 text-orange-700 dark:text-orange-400 border border-orange-300 dark:border-orange-500'
                                                                        : 'bg-violet-100 dark:bg-violet-500/20 text-violet-700 dark:text-violet-400 border border-violet-300 dark:border-violet-500'
                                                                : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 border border-transparent'
                                                                }`}
                                                        >
                                                            {p.charAt(0).toUpperCase() + p.slice(1)}
                                                        </button>
                                                    ))}
                                                </div>
                                            </motion.div>
                                        )}

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                                Email (optional) <span className="text-gray-400 font-normal">– for follow-up</span>
                                            </label>
                                            <input
                                                type="email"
                                                value={formData.email}
                                                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                                                placeholder="your@email.com"
                                                className="w-full px-4 py-3 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-violet-500/50 focus:border-violet-500"
                                            />
                                        </div>

                                        <button
                                            type="submit"
                                            disabled={loading}
                                            className="w-full py-3.5 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-semibold rounded-xl hover:opacity-90 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                                        >
                                            {loading ? (
                                                <>
                                                    <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                                                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                                    </svg>
                                                    Submitting...
                                                </>
                                            ) : (
                                                <>
                                                    Submit Feedback
                                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                                                    </svg>
                                                </>
                                            )}
                                        </button>
                                    </form>
                                </div>
                            )}
                        </motion.div>
                    )}

                    {/* FAQ Tab */}
                    {activeTab === 'faq' && (
                        <motion.div
                            key="faq"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            className="space-y-4"
                        >
                            {faqs.map((faq, i) => (
                                <motion.div
                                    key={i}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: i * 0.1 }}
                                    className="bg-white dark:bg-[#1C1C1E] rounded-2xl border border-gray-200 dark:border-gray-800 p-6"
                                >
                                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2 flex items-start gap-3">
                                        <span className="text-violet-500">Q:</span>
                                        {faq.q}
                                    </h3>
                                    <p className="text-gray-600 dark:text-gray-400 pl-7">
                                        {faq.a}
                                    </p>
                                </motion.div>
                            ))}

                            <div className="text-center py-6">
                                <p className="text-gray-500 dark:text-gray-400 mb-4">Still have questions?</p>
                                <button
                                    onClick={() => setActiveTab('feedback')}
                                    className="px-6 py-3 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-semibold rounded-xl hover:opacity-90 transition-all"
                                >
                                    Send us a message
                                </button>
                            </div>
                        </motion.div>
                    )}

                    {/* Contact Tab */}
                    {activeTab === 'contact' && (
                        <motion.div
                            key="contact"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            className="grid md:grid-cols-2 gap-6"
                        >
                            <div className="bg-white dark:bg-[#1C1C1E] rounded-2xl border border-gray-200 dark:border-gray-800 p-8 text-center">
                                <div className="w-16 h-16 bg-violet-100 dark:bg-violet-500/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
                                    <span className="text-3xl">📧</span>
                                </div>
                                <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Email Us</h3>
                                <p className="text-gray-600 dark:text-gray-400 text-sm mb-4">
                                    For detailed inquiries and support
                                </p>
                                <a
                                    href="mailto:support@planorah.me"
                                    className="text-violet-600 dark:text-violet-400 font-medium hover:underline"
                                >
                                    support@planorah.me
                                </a>
                            </div>

                            <div className="bg-white dark:bg-[#1C1C1E] rounded-2xl border border-gray-200 dark:border-gray-800 p-8 text-center">
                                <div className="w-16 h-16 bg-blue-100 dark:bg-blue-500/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
                                    <span className="text-3xl">💬</span>
                                </div>
                                <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Social Media</h3>
                                <p className="text-gray-600 dark:text-gray-400 text-sm mb-4">
                                    Follow us for updates and tips
                                </p>
                                <div className="flex justify-center gap-4">
                                    <a href="#!" className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
                                        Twitter/X
                                    </a>
                                    <a href="#!" className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
                                        LinkedIn
                                    </a>
                                </div>
                            </div>

                            <div className="md:col-span-2 bg-gradient-to-r from-violet-500 to-purple-600 rounded-2xl p-8 text-center text-white">
                                <h3 className="text-xl font-bold mb-2">We Value Your Feedback</h3>
                                <p className="text-white/80 mb-4">
                                    Every piece of feedback helps us make Planorah better for students like you.
                                </p>
                                <button
                                    onClick={() => setActiveTab('feedback')}
                                    className="px-6 py-3 bg-white text-violet-600 font-semibold rounded-xl hover:opacity-90 transition-all"
                                >
                                    Share Your Thoughts
                                </button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
