# Generated by Django 5.2.5 on 2026-02-25 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('trigger', models.CharField(choices=[('onboarding_complete', 'Onboarding Complete'), ('manual', 'Manual Trigger')], default='onboarding_complete', max_length=50)),
                ('call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='initiated', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Call Log',
                'verbose_name_plural': 'AI Call Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
