# Generated by Django 5.2.7 on 2025-11-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='roadmap',
            name='career_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='goal',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('resources', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='roadmap_ai.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('estimated_hours', models.IntegerField(default=0)),
                ('tech_stack', models.JSONField(default=list)),
                ('learning_outcomes', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='roadmap_ai.milestone')),
            ],
        ),
        migrations.DeleteModel(
            name='RoadmapStep',
        ),
    ]
