# Generated by Django 5.2.7 on 2025-11-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0002_alter_roadmap_options_roadmap_career_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='estimated_duration',
            field=models.CharField(blank=True, default='Not specified', max_length=100),
            preserve_default=False,
        ),
    ]
