# Generated by Django 5.2.7 on 2025-11-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0003_alter_roadmap_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='estimated_duration',
            field=models.CharField(blank=True, default='6 months', max_length=100),
        ),
    ]
