# Generated by Django 5.2.7 on 2025-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0004_alter_roadmap_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
