# Generated by Django 5.2.5 on 2025-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0005_milestone_end_date_milestone_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='skills',
        ),
        migrations.AddField(
            model_name='milestone',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='daily_commitment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
