# Generated by Django 5.2.5 on 2025-11-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0006_rename_completed_milestone_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='category',
            field=models.CharField(choices=[('project', 'Project-Based'), ('career', 'Career Path'), ('research', 'Research & Academia')], default='career', max_length=20),
        ),
    ]
