# Generated by Django 5.2.5 on 2025-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0007_roadmap_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='learning_constraints',
            field=models.TextField(blank=True, help_text='Time, budget, or resource constraints'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='motivation_style',
            field=models.CharField(blank=True, default='Milestones', max_length=50),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='output_format',
            field=models.CharField(blank=True, default='Milestone-based', max_length=50),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='success_definition',
            field=models.TextField(blank=True, help_text='How success is defined'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='tech_stack',
            field=models.TextField(blank=True, help_text='Preferred tech stack or domain'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='category',
            field=models.CharField(choices=[('project', 'Project-Based'), ('career', 'Career Path'), ('research', 'Research & Academia'), ('skill_mastery', 'Skill Mastery')], default='career', max_length=20),
        ),
    ]
