# Generated by Django 5.2.5 on 2025-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0008_roadmap_learning_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
