# Generated by Django 6.0 on 2025-12-31 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0009_roadmap_faqs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('source_type', models.CharField(choices=[('upload', 'Upload (ZIP/Folder)'), ('git_url', 'Git Repository URL'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('git_url', models.URLField(blank=True, help_text='Original Git repository URL', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to uploaded files', max_length=500)),
                ('github_url', models.URLField(blank=True, help_text='Published GitHub URL', null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Project',
                'verbose_name_plural': 'Student Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
