# Generated by Django 5.2.7 on 2026-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0010_studentproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Date of the exam', null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='exam_name',
            field=models.CharField(blank=True, help_text='Name of the exam/paper', max_length=255),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='syllabus_text',
            field=models.TextField(blank=True, help_text='Pasted syllabus content'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='category',
            field=models.CharField(choices=[('project', 'Project-Based'), ('career', 'Career Path'), ('research', 'Research & Academia'), ('skill_mastery', 'Skill Mastery'), ('exam_prep', 'Exam Preparation')], default='career', max_length=20),
        ),
    ]
