# Generated by Django 5.2.5 on 2026-01-16 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_ai', '0011_roadmap_exam_date_roadmap_exam_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField(help_text='Measurable outcome - what needs to be proven')),
                ('description', models.TextField(blank=True, help_text='Additional context or instructions')),
                ('proof_type', models.CharField(choices=[('GITHUB_REPO', 'GitHub Repository'), ('QUIZ', 'Quiz/Assessment'), ('FILE_UPLOAD', 'File Upload (PDF/ZIP)'), ('URL', 'Live URL/Deployment')], help_text='Type of acceptable proof', max_length=20)),
                ('validator_type', models.CharField(choices=[('AUTO_GITHUB', 'Automated GitHub Validator'), ('AUTO_QUIZ', 'Automated Quiz Validator'), ('MANUAL', 'Manual Human Review')], help_text='How proof will be validated', max_length=20)),
                ('acceptance_rules', models.JSONField(default=dict, help_text='Validator-specific rules. For GitHub: min_commits, required_files, required_keywords')),
                ('min_pass_score', models.IntegerField(default=70, help_text='Minimum score (0-100) to pass')),
                ('max_attempts', models.IntegerField(blank=True, help_text='Max attempts allowed (null = unlimited)', null=True)),
                ('is_core_task', models.BooleanField(default=False, help_text='Core tasks required for output eligibility')),
                ('order', models.IntegerField(default=0, help_text='Display order within roadmap/milestone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap_ai.milestone')),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap_ai.roadmap')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
