# Generated by Django 5.2.5 on 2026-02-27 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_source', models.CharField(help_text='Origin section, e.g. "roadmap", "dashboard", "tasks"', max_length=100)),
                ('student_goal', models.TextField(blank=True, default='')),
                ('current_progress', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(help_text='User input / conversation transcript')),
                ('mentor_message', models.TextField(blank=True, default='', help_text='AI mentor response')),
                ('emotional_tone', models.CharField(blank=True, choices=[('encouraging', 'Encouraging'), ('empathetic', 'Empathetic'), ('motivating', 'Motivating'), ('neutral', 'Neutral'), ('supportive', 'Supportive'), ('challenging', 'Challenging'), ('celebratory', 'Celebratory')], default='neutral', max_length=50)),
                ('confidence_level', models.FloatField(default=0.0, help_text='0.0 to 1.0 scale')),
                ('clarity_level', models.FloatField(default=0.0, help_text='0.0 to 1.0 scale')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='List of suggested action items')),
                ('session_summary', models.TextField(blank=True, default='', help_text='Concise summary for memory across sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Mentoring Session',
                'verbose_name_plural': 'Student Mentoring Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
