# Generated by Django 5.2.5 on 2026-04-22 08:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='month_year',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-(0[1-9]|1[0-2])$', 'Format must be YYYY-MM')]),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='session_boo_user_id_7b873f_idx'),
        ),
    ]
