from django.db import models
from django.conf import settings


class Subject(models.Model):
    """Represents a course/subject a student is studying for an exam."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='planora_subjects',
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    exam_date = models.DateField(null=True, blank=True)
    # Raw text extracted from the uploaded syllabus
    syllabus_text = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} – {self.name}"


class ExamPattern(models.Model):
    """Exam marks distribution linked to a Subject."""

    subject = models.OneToOneField(
        Subject,
        on_delete=models.CASCADE,
        related_name='exam_pattern',
    )
    # e.g. [{"marks": 2, "count": 10, "type": "MCQ"}, {"marks": 5, "count": 5, "type": "Short"}, ...]
    marks_distribution = models.JSONField(default=list)
    total_marks = models.IntegerField(default=0)
    duration_minutes = models.IntegerField(default=180)
    notes = models.TextField(blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Exam pattern for {self.subject.name}"


class Topic(models.Model):
    """A single topic inside a Subject."""

    IMPORTANCE_CHOICES = [
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
    ]

    DEPTH_CHOICES = [
        ('short', 'Short Answer'),
        ('medium', 'Medium Answer'),
        ('long', 'Long Answer'),
    ]

    STATUS_CHOICES = [
        ('not_started', 'Not Started'),
        ('weak', 'Weak'),
        ('strong', 'Strong'),
    ]

    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
        related_name='topics',
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    importance = models.CharField(max_length=10, choices=IMPORTANCE_CHOICES, default='medium')
    depth = models.CharField(max_length=10, choices=DEPTH_CHOICES, default='medium')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='not_started')
    confidence = models.IntegerField(default=0)  # 0–100
    order = models.IntegerField(default=0)
    # Subtopics and expected questions generated by AI
    subtopics = models.JSONField(default=list, blank=True)
    expected_questions = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['order', 'created_at']

    def __str__(self):
        return f"{self.subject.name} – {self.name}"


class GeneratedNotes(models.Model):
    """AI-generated exam-ready notes for a Topic."""

    topic = models.OneToOneField(
        Topic,
        on_delete=models.CASCADE,
        related_name='notes',
    )
    # Structured content: {definition, explanation, key_points, examples, conclusion}
    content = models.JSONField(default=dict)
    raw_text = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Notes for {self.topic.name}"


class StudyGuide(models.Model):
    """AI-generated step-by-step study guide for a Topic."""

    topic = models.OneToOneField(
        Topic,
        on_delete=models.CASCADE,
        related_name='study_guide',
    )
    # Structured content: {order_of_learning, key_focus_areas, common_mistakes, revision_strategy}
    content = models.JSONField(default=dict)
    raw_text = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Study guide for {self.topic.name}"


class StudyPlan(models.Model):
    """AI-generated daily study plan for a Subject."""

    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
        related_name='study_plans',
    )
    exam_date = models.DateField()
    daily_hours = models.FloatField(default=2.0)
    # List of {date, topics: [{topic_id, topic_name, duration_minutes, focus}], notes}
    plan_data = models.JSONField(default=list)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Study plan for {self.subject.name} – exam {self.exam_date}"
