# Generated by Django 5.2.5 on 2025-12-05 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField()),
                ('job_description', models.TextField()),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('match_score', models.IntegerField(default=0)),
                ('missing_keywords', models.JSONField(default=list)),
                ('strength_areas', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('summary_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
