# Generated by Django 5.2.5 on 2025-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deleted User',
                'verbose_name_plural': 'Deleted Users',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
