# Generated by Django 5.2.5 on 2026-01-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_universal_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('class_9_10', 'Class 9-10'), ('class_11_12', 'Class 11-12'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd_research', 'PhD / Research'), ('professional', 'Professional / Other')], help_text='Current education stage of the user', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete onboarding data specific to education stage'),
        ),
    ]
