# Generated by Django 5.2.7 on 2026-03-12

from django.db import migrations, models


def backfill_user_status(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all().only('id', 'is_active', 'is_verified'):
        if user.is_verified and user.is_active:
            status = 'active'
        elif not user.is_verified:
            status = 'pending'
        else:
            status = 'suspended'
        CustomUser.objects.filter(id=user.id).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_education_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('active', 'Active'),
                    ('suspended', 'Suspended'),
                    ('deleted', 'Deleted'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_user_status, migrations.RunPython.noop),
    ]
